layer=overlay
anchor=top
# ymargin=20

font=GohuFont uni14 Nerd Font:size=12
prompt="❯ "
lines=10
width=40
horizontal-pad=20
vertical-pad=15
inner-pad=5
# Optional: use a dark icon theme if you have one installed
# icon-theme=Papirus-Dark 

# Load Pywal's generated colors
include=~/.cache/wal/fuzzel.ini

[border]
width=1
radius=8
