[main]
font=GohuFont uni14 Nerd Font:size=11
pad=14x14
dpi-aware=no
selection-target=primary

# Load Pywal's generated colors
include=~/.cache/wal/colors-foot.ini

[cursor]
style=beam
blink=yes

[csd]
border-width=2
