# ~/.config/hypr/hyprpaper.conf

# Import source from pywal
source = ~/.cache/wal/colors-hyprland

# Laptop Monitor
wallpaper {
    monitor = eDP-1
    path = $wallpaper
    fit_mode = cover
}

# Fallback Monitor
wallpaper {
    monitor = 
    path = $wallpaper
    fit_mode = cover
}

splash = false
ipc = on
